title: "Jorge Pais"
author: "Jorge Pais"
description: "Art && Engineering" # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "up201904841@edu.fe.up.pt"
github_username: "jorge-pais"
linkedin_username: "jorg3-pais"
#twitter_username: "twitteruser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
remote_theme: tareqdandachi/jekyll-shell-theme 
#theme: minima

rss: rss

highligher: rogue

header_pages:
  - index.md
  - archive.md
  - about.md
    
plugins:
  - jemoji
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
